// <auto-generated />
using Ecclesiastical.Treasury.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecclesiastical.Treasury.App.Migrations
{
    [DbContext(typeof(EcclesiasticalDbContext))]
    [Migration("20230612232005_User changes")]
    partial class Userchanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ecclesiastical.Treasury.App.Data.FinancialCategory", b =>
                {
                    b.Property<int>("FinancialCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FinancialGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("FinancialCategoryId");

                    b.ToTable("FinancialCategories");
                });

            modelBuilder.Entity("Ecclesiastical.Treasury.App.Data.FinancialGroup", b =>
                {
                    b.Property<int>("FinancialGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("FinancialGroupId");

                    b.ToTable("FinancialGroups");
                });

            modelBuilder.Entity("Ecclesiastical.Treasury.App.Data.FinancialMovement", b =>
                {
                    b.Property<int>("FinancialMovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FinancialSubcategoryId")
                        .HasColumnType("int");

                    b.Property<int>("FinancialUserId")
                        .HasColumnType("int");

                    b.HasKey("FinancialMovementId");

                    b.ToTable("FinancialMovements");
                });

            modelBuilder.Entity("Ecclesiastical.Treasury.App.Data.FinancialSubcategory", b =>
                {
                    b.Property<int>("FinancialSubcategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FinancialCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("FinancialSubcategoryId");

                    b.ToTable("FinancialSubcategories");
                });

            modelBuilder.Entity("Ecclesiastical.Treasury.App.Data.FinancialUser", b =>
                {
                    b.Property<int>("FinancialUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FinancialSubcategoryId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.HasKey("FinancialUserId");

                    b.ToTable("FinancialUsers");
                });

            modelBuilder.Entity("Ecclesiastical.Treasury.App.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
